### ISSUE TITLE
Interfaces needed from Front-End

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#1]
Requirements & Issues
1. 用user_id获取
----a. 用户名
----b. 用户头像
----c. 用户在地图的头像（和个人头像不同），这些头像是系统自带的，可选择的有限，返回的时候做成int类型即可，我用index内部索引
2. 用comment_id获取
----a. comment_pin被点赞的总数
----b. comment_pin被评论的总数及具体的评论人、评论时间、评论内容、该条评论被点赞的数目
3. 根据老板的设计，（沟通过了），评论是不可以被unlike，点了like就不可取消，因为有个很有趣的动画需要实现，算是亮点吧
4. 目前获取随机生成的其他用户的位置不够随机，隐私保护得不是很好，范围可以再扩大一些，每次可以只返回一个随机点，不需要五个

**Comment by GreatYYX** [comment]
1. 本周会添加profile接口用于通过user_id获取user_name, mini_avatar, 普通avatar已经有现成的接口了。以后注意区分account接口和profile接口，account接口只能用户自身set/get，profile不光可以用户自身set/get，其他用户也能get。
2. 接口已经做好。
3. 动画和uncomment应该不冲突吧……不过我们接口给你们留了，你们可以考虑不调用。
4. 这个不知道是不是理解上的偏差，当时的需求是显示一个随机范围，所以我们给你直接随机了5个点，如果只随机1个点，你们再在这个基础上随机，那范围就更加不准确了；如果直接给你们中心点让你们随机，那相当于事实上没有随机（也就是随机这个过程必须后端做）。范围可以给你再扩大，你们定个你们需要的数值给我，目前随机范围是50m-200m。

**Comment by joshuayueshen** [comment]
好的，
前面3点都okay，我会去测试
4. 目前感觉没有50m-200m，感觉是50m之内（是地图上给用户的直观感觉），我目前的做法也确实是五个随机点中随便挑一个使用。可以有空见面演示一下，到时候再改，先可以不动。

**Comment by GreatYYX** [comment]
随机范围已经更新到200了。
其余接口都已经实现，目前获取某个pin所有信息的接口是独立的：https://github.com/letsfae/Fae-Backend/blob/master/docs_zh_cn/protocol_pins.md#获取pin属性-white_check_mark ， 我们会考虑合成到已经存在的接口中。
