### ISSUE TITLE
Sync: 判断user是否离开app回到主界面

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#10]
目前有这样的一个需求，不知后端同事们觉得实现的困难度有多大？

目前，只要user用mobile app登录系统，fae app会给后端服务器发送位置信息，那么其他人能在范围内实时地get到其他user的unaccurate的location，但是目前如果用户离开app返回主界面，服务器还是会给在使用app的user发送该用户的信息（即使他已经离开app返回主界面了）

想问一下后端，如果近期要实现用户一定时间不给后端发送gps location了以后，get map这个interface不给其他用户发送这位离开app的用户的location信息的  这个功能有多难？很希望这个功能能早点实现。

还请告知可行性啦！^_^
愿你们工作愉快

**Comment by GreatYYX** [comment]
如果是，后端可以根据时间过滤，当然前端也可以根据时间过滤。
所以先明确一下需求和谁来做的问题，如果需要做我们可以做的。
当然如果后端做，估计应该会给你们一个参数，让你们选择显示的时间范围。
