### ISSUE TITLE
[用户注册] case sensitivity - 应为不敏感，即aaa和aAa视为相同用户

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#100]
1. 应为不敏感，即aaa和aAa视为相同用户。文档里也是这么写的，但经过测试发现，后端返回status code为500.
2. 此外，用户如果在注册的时候使用aAa来注册，那么往后的显示也为aAa，而非aaa。登录的时候不敏感
3. "-", "_", "."只允许出现一个，不能多个同时出现

辛苦啦。

**Comment by GreatYYX** [comment]
@MrBlueberry 登录时候对比判断的时候大小写不敏感 但是数据保存和返回时候是有大小写的
