### ISSUE TITLE
[需求][Pin-Action] update pin comments

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#102]
目前pin-action-comment的功能有：
post a new comment
get a comment or comments
delete a comment
需要添加而外一条：
update a comment

**Comment by GreatYYX** [comment]
pin comment还要编辑啊？好的吧……我记得评论貌似一般都不提供编辑的吧 一般都是直接删了（微博不光是评论，微博本身都不允许编辑啊……）

**Comment by joshuayueshen** [comment]
😔 我也说了同样的理由，但。。。

**Comment by GreatYYX** [comment]
好吧 那就搞～
