### ISSUE TITLE
【bug】获取https://dev.letsfae.com/pins/statistics时候返回了405错误, 但是已经是当前用户登录状态了。

### ISSUE THREAD

**Issue by weishiqi** [letsfae/Fae-Backend#104]
https://dev.letsfae.com/pins/statistics 
虽然是当前用户已经登录了，而且获取其他api都可以，但这个api一直返回405。
返回如下：
"message": "405 Method Not Allowed",
  "status_code": 405,
  "debug": {
    "line": 218,
    "file": "/usr/share/nginx/html/dev/Fae-Backend/Laravel/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php",
    "class": "Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException",

**Comment by GreatYYX** [comment]
OK i'll fix it~ thx

**Comment by GreatYYX** [comment]
这个接口还没有更新到服务器上，所以还用不了，下周更新服务器时候就可以用了。

**Comment by GreatYYX** [comment]
另外，因为后端把place认为是一种pin，为了防止歧义，最后统计的时候我们把每种类型都给拆开了，前端可以自己累加。
```
{
	"user_id": @number,
	"count": {
		"created_comment_pin": @number,
		"created_media_pin": @number,
		"saved_comment_pin": @number,
		"saved_media_pin": @number,
		"saved_place_pin": @number
	}
}
```

**Comment by weishiqi** [comment]
好的
