### ISSUE TITLE
[获取头像] 协议上写着需要auth，但实际不用？是bug吗？

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#108]
![image](https://cloud.githubusercontent.com/assets/18542103/25776372/34709dcc-3271-11e7-829f-c792b1ef5004.png)

@GreatYYX

**Comment by SonnyYang** [comment]
是他的typo吧？当初所有的图像获取接口都是不需要auth的，这么做是AT提的要求好像，说是你们前端用的库的需求。

**Comment by GreatYYX** [comment]
所有的图像获取（不包括文件）都不需要auth，这是at当时的要求（他说你们的库不能自定义header，我建议如果能加auth就加上，这样才是最合理的）。协议有些可能当时没改。

**Comment by joshuayueshen** [comment]
好的，我研究一下，我也建议加上，我寻求一下解决方法

**Comment by joshuayueshen** [comment]
@GreatYYX 
请求加入使用auth来get user avatar，之前AT的老方法被我替代了，已经寻求到了新的方法。新方法可以支持auth的加入，如果implement好了，还请暂时不关闭这个issue直到测试成功或摒弃。

**Comment by GreatYYX** [comment]
好的 那我就把所有的这些图片get的接口换成auth required了

**Comment by joshuayueshen** [comment]
好的

**Comment by joshuayueshen** [comment]
it works fine!
