### ISSUE TITLE
SignUpUser  Existence Check

### ISSUE THREAD

**Issue by Sophieeeee** [letsfae/Fae-Backend#109]
目前，在新的user signup检查username是否存在时，后端判断return出的boolean值有错

在RegisterConfirmViewController中signUpUser()里的status显示为422，也就是username已存在，不能signup。

而在postman里check username existence，return的是false，也就是用户不存在，可以signup。

**Comment by joshuayueshen** [comment]
![image](https://user-images.githubusercontent.com/18542103/27255289-2d5e14b0-5350-11e7-9fff-4658b4468bf2.png)
![image](https://user-images.githubusercontent.com/18542103/27255291-37874f7e-5350-11e7-89ce-b84900499b24.png)
@MrBlueberry

**Comment by MrBlueberry** [comment]
已解决
