### ISSUE TITLE
map(user)接口新添加数据

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#110]
目前map(user)的api包含了type, user_id, mini_avatar, geolocation信息，请问可否添加上user的nickname, short_intro, age, gender 信息呢（虽然这些信息在NameCard中可以进行二次获取）

 {
    "type": "user",
    "user_id": 107,
    "mini_avatar": 0,
    "geolocation": [
      {
        "latitude": 34.021809299324,
        "longitude": -118.29072431811
      },
      {
        "latitude": 34.02786197441,
        "longitude": -118.29331169035
      },
      {
        "latitude": 34.031135040682,
        "longitude": -118.28842417203
      },
      {
        "latitude": 34.030347728593,
        "longitude": -118.29085073006
      },
      {
        "latitude": 34.030459074024,
        "longitude": -118.2887311716
      }
    ],
    "created_at": "2017-05-30 22:19:39"
  }

**Comment by GreatYYX** [comment]
下次更新会加入
