### ISSUE TITLE
map(place)中数据重复问题

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#111]
map(place)中存在除place_id不同，其他信息完全相同的数据重复问题，麻烦后端查看解决一下。

  {
    "place_id": 1132,
    "name": "Pizza Studio",
    "categories": [
      "Pizza",
      "Salad"
    ],
    "geolocation": {
      "latitude": 34.0252636197,
      "longitude": -118.287763141
    },
    "country": "United States",
    "state": "CA",
    "address": "3584 S Figueroa StLos Angeles, CA 90007",
    "zip_code": 90007
  },
  {
    "place_id": 1012,
    "name": "Pizza Studio",
    "categories": [
      "Pizza",
      "Salad"
    ],
    "geolocation": {
      "latitude": 34.0252636197,
      "longitude": -118.287763141
    },
    "country": "United States",
    "state": "CA",
    "address": "3584 S Figueroa StLos Angeles, CA 90007",
    "zip_code": 90007
  }

**Comment by GreatYYX** [comment]
好的 多谢反馈 不过现在数据主要用来给前端测试 后端估计要放弃yelp数据换一个数据源重新爬了……
