### ISSUE TITLE
20170616 new features

### ISSUE THREAD

**Issue by GreatYYX** [letsfae/Fae-Backend#114]
1. follower / followee
2. get friend list
3. username prefix --> uid (info in resp: is friend, blocked, requested)
4. bulk query (we can make partial bulk query, a bulk query for a specific api)
5. change pagination from relative to absolute

----

1. admin

**Comment by GreatYYX** [comment]
@maplestory06

**Comment by joshuayueshen** [comment]
抱歉老姚，我有点忘记第四点和第五点是什么了

**Comment by joshuayueshen** [comment]
是否可以帮忙解答一下？ @GreatYYX

**Comment by GreatYYX** [comment]
4是批量接口，5是分页的方式。批量从search已经开始了，其他接口需要有一个过渡，分页那个还是决定采用原来的方案，毕竟不是主要功能。这个issue先关掉了。
