### ISSUE TITLE
foursquare category list

### ISSUE THREAD

**Issue by SonnyYang** [letsfae/Fae-Backend#115]
Athletics &amp; Sports
Wine Bar
Playground
Italian Restaurant
Sake Bar
Shopping Mall
French Restaurant
Korean Restaurant
Gym
Buffet
Organic Grocery
Skate Park
Bookstore
Middle Eastern Restaurant
Japanese Restaurant
Pool
Sushi Restaurant
Building
Bagel Shop
Bar
Dive Bar
Martial Arts Dojo
Southern / Soul Food Restaurant
Jewelry Store
Music Store
Hot Dog Joint
Ice Cream Shop
Bakery
Theme Park
Filipino Restaurant
Salad Place
Coffee Shop
Gourmet Shop
Kosher Restaurant
College Classroom
Spa
Beer Store
Grocery Store
Seafood Restaurant
Concert Hall
Arcade
Climbing Gym
Museum
Indie Theater
Pharmacy
Rock Club
Cycle Studio
Cosmetics Shop
South American Restaurant
Sports Bar
Gym / Fitness Center
Vegetarian / Vegan Restaurant
Park
Halal Restaurant
Scenic Lookout
Convenience Store
Art Museum
Candy Store
Theater
Caribbean Restaurant
Clothing Store
Plaza
Moving Target
New American Restaurant
Steakhouse
Farmers Market
Burrito Place
Beer Bar
Peruvian Restaurant
Liquor Store
Accessories Store
Pet Store
Donut Shop
Wine Shop
Canal
Furniture / Home Store
Gastropub
Street Food Gathering
Performing Arts Venue
Cajun / Creole Restaurant
Irish Pub
Food Truck
Hookah Bar
Science Museum
Sporting Goods Shop
Pilates Studio
Burger Joint
Art Gallery
Hotel
Asian Restaurant
Trail
Fried Chicken Joint
Chinese Restaurant
Falafel Restaurant
Ethiopian Restaurant
Frozen Yogurt Shop
Gymnastics Gym
Music Venue
College Bookstore
Noodle House
Metro Station
Smoke Shop
Latin American Restaurant
Mexican Restaurant
Whisky Bar
Thai Restaurant
Business Service
Library
Supermarket
Snack Place
Massage Studio
Antique Shop
Market
Cocktail Bar
Construction &amp; Landscaping
Restaurant
Lake
Breakfast Spot
Flower Shop
Hotel Bar
Dessert Shop
Beach
Light Rail Station
Food Court
Sandwich Place
Garden
Women&#39;s Store
Food
Fast Food Restaurant
Paper / Office Supplies Store
Brewery
Leather Goods Store
Deli / Bodega
Mediterranean Restaurant
Indonesian Restaurant
Beer Garden
Diner
Vietnamese Restaurant
Pizza Place
Ramen Restaurant
Airport
Baseball Stadium
Arts &amp; Crafts Store
Photography Studio
Outdoor Sculpture
Soccer Field
Caf\xc3\xa9
American Restaurant
Speakeasy
Rental Car Location
Taco Place
Juice Bar
Gift Shop
BBQ Joint
Health &amp; Beauty Service
Hawaiian Restaurant

**Comment by joshuayueshen** [comment]
@LintaLinxi

**Comment by joshuayueshen** [comment]
What should we do next? Double check the list with the list from Boss?

**Comment by GreatYYX** [comment]
@maplestory06 测试数据1000条所含有的unique category。你们需要把这些对应到你们要的类别上！

**Comment by joshuayueshen** [comment]
@GreatYYX 嗯好的！
