### ISSUE TITLE
charcontroller里边getunread问题

### ISSUE THREAD

**Issue by kaiqianz** [letsfae/Fae-Backend#116]
判断if(is_null($last_message_sender))多余，因为chat 表里边last_message_sender_id是外键。
![image](https://user-images.githubusercontent.com/16984097/27421107-7c06348a-575b-11e7-8ea3-e254283d9a49.png)

![image](https://user-images.githubusercontent.com/16984097/27421077-5893a780-575b-11e7-958f-203bcaab40a6.png)
@MrBlueberry

**Comment by GreatYYX** [comment]
@kaiqianz 这类tag不叫duplicated，tag是用来标定issue之间的关系的，duplicated意思是有人发过相同的issue了，基本测试出来的问题都可以认为是bug
