### ISSUE TITLE
[Contacts] add some required section in response of APIs

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#119]
GET /friends/request
	add request_user_user_name
	add request_user_nick_name
	add request_user_age (if show_age is true)
	add request_user_gender (is show_gender is true)

GET /friends
	add request_user_user_name
	add request_user_nick_name
	add request_user_age (if show_age is true)
	add request_user_gender (is show_gender is true)

GET /follows/:user_id/follower
	add request_user_user_name
	add request_user_nick_name
	add request_user_age (if show_age is true)
	add request_user_gender (is show_gender is true)

GET /follows/:user_id/followee
	add request_user_user_name
	add request_user_nick_name
	add request_user_age (if show_age is true)
	add request_user_gender (is show_gender is true)

**Comment by GreatYYX** [comment]
老板设计中，show_user_name这个选项，是只在namecard上生效还是对朋友也有效

**Comment by joshuayueshen** [comment]
sorry for late response。对朋友也有效
