### ISSUE TITLE
请问“获取其他用户资料 get profile”这个能用了吗？

### ISSUE THREAD

**Issue by jjdddn1** [letsfae/Fae-Backend#12]
返回文件是怎么样的呢？

**Comment by GreatYYX** [comment]
已经写好，还没有上线，上线时候会通知前端。
目前范围内容如下：

```
 {
     "user_name": @string,
     "mini_avatar": @number
 }
```

profile接口会具有两大功能：1.普通的字段设置和获取 2.作为account的包装了权限的wrapper

**Comment by jjdddn1** [comment]
对了，能不能返回的时候增加一个user_id,这样感觉可以省好多事儿。

**Comment by GreatYYX** [comment]
可以的，主要是因为传入的时候需要user_id了……所以我设计接口的时候就认为你是有user_id的，当然你要的话我给你加上好了

**Comment by jjdddn1** [comment]
麻烦了，多谢
