### ISSUE TITLE
[GET] /pins/statistics - 缺少created_chat_room字段

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#122]
![image](https://user-images.githubusercontent.com/18542103/27599231-eeb81a2e-5b1c-11e7-990d-92fd1420fc58.png)

@GreatYYX @MrBlueberry

**Comment by GreatYYX** [comment]
收到 这个当时没想到要做

**Comment by MrBlueberry** [comment]
已添加
