### ISSUE TITLE
[POST / GET / UPDATE] chat_room需要一张图片作为聊天室头像 

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#123]
![image](https://user-images.githubusercontent.com/18542103/27601142-1665299e-5b23-11e7-8a76-48c023fea04f.png)
@GreatYYX @MrBlueberry

**Comment by GreatYYX** [comment]
@maplestory06 这个4月份的时候做了 可能当时我漏了通知或者你们没看到吧 [传送门](https://github.com/letsfae/FaeMap-Backend/blob/master/docs_zh_cn/protocol_files.md#设置聊天室cover_image)
