### ISSUE TITLE
MediaController中gerfromuser

### ISSUE THREAD

**Issue by kaiqianz** [letsfae/Fae-Backend#125]
出现comment_pin，不对
<img width="934" alt="screen shot 2017-07-06 at 3 58 50 pm" src="https://user-images.githubusercontent.com/16984097/27901301-243bd318-6264-11e7-977b-ead0e3a361f8.png">
<img width="478" alt="screen shot 2017-07-06 at 3 59 56 pm" src="https://user-images.githubusercontent.com/16984097/27901321-31e8331c-6264-11e7-8b2f-ff7af600ca76.png">
@MrBlueberry

**Comment by MrBlueberry** [comment]
已解决
