### ISSUE TITLE
GET /chats 这个接口的返回内容里面能不能添加一条with_user_name?

### ISSUE THREAD

**Issue by jjdddn1** [letsfae/Fae-Backend#13]
我觉得目前用with_user_id再去请求name有点多此一举，服务器来做这个可能会快一点...

**Comment by GreatYYX** [comment]
这个问题我们已经注意到了，目前没有在所有user_id的地方返回user_name的原因是：“不知道你们需要的用户相关信息是什么”；比如你现在可能只需要用户名，后面可能需要小头像了，有的可能需要性别（而且性别还能在后续功能中定义是否有权限获取），因此API层的冗余到什么程度我目前还不清楚，需要和你们完整的讨论过才可以，毕竟我们也希望减少调用次数。

**Comment by jjdddn1** [comment]
对的，其实Avatar也是需要的。
目前来讲，因为我要生成一个最近聊天列表，按照老板的设计，每一个单元格里面有对象头像，对象名字，上一条消息内容，上一条消息距现在时间，以及未读消息数量。也就是GET /chats里面需要这些东西...当然我也可以拿到对方id以后再去get 头像和名字，不过那又是一次请求。

**Comment by GreatYYX** [comment]
除非是mini_avatar（数字），头像作为图片一定是单独的http请求（不能避免的），我现在争取把你需要用到的字段一次性都返回给你。你可以统计下你用到的每个接口还需要的字段，写在issue里面或者周六时候统一告诉我，我可以给你补上。

**Comment by jjdddn1** [comment]
我看了一下，目前只需要这些：
GET /chats/unread
Server_send_time:

GET /chats
Server_send_time:
with_user_name:

那个 server_send_time是我瞎起的名字，就是服务器发送该消息的时间。
然后user的头像是不是通过 files/users/:user_id/avatar/ 就可以下到?

**Comment by GreatYYX** [comment]
没错
