### ISSUE TITLE
使用不存在的user_name登录时提示status 500

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#130]
当使用未注册过的email登录时，提示错误如下图（status 404, 正确）：
![image](https://user-images.githubusercontent.com/28714568/28132797-c2134ee4-66f2-11e7-9046-2478fecbd3da.png)

当使用未注册过的user_name登录时，提示错误如下图（status 500, 错误）：
![image](https://user-images.githubusercontent.com/28714568/28132900-161c49fa-66f3-11e7-95c4-4a00983b287d.png)

麻烦check一下这个问题，谢谢！

**Comment by MrBlueberry** [comment]
已解决
