### ISSUE TITLE
[Contacts] New API endpoint needed

### ISSUE THREAD

**Issue by justinhe16** [letsfae/Fae-Backend#133]
1) A list of requests that the current user has sent
2) A POST request to withdraw a request
3) A POST request to resend a request

**Comment by GreatYYX** [comment]
2 and 3 will be added. the 1st endpoint is already there, check it [here ](https://github.com/letsfae/FaeMap-Backend/blob/master/docs_zh_cn/protocol_contacts.md#获取所有好友请求-white_check_mark).

**Comment by justinhe16** [comment]
@maplestory06 @GreatYYX Thank you! One thing though -- I think the endpoint you linked me too is not the one I'm looking for. Does backend have an endpoint for the requests I (the user) sent? (For example, if I send a request to you and id#150, I need an endpoint that tells me I sent those two requests). Please let me know!

**Comment by joshuayueshen** [comment]
@GreatYYX 
老姚，Justin提到的第一个接口说的是获取当前用户(Current User)所有发出的请求，而不是所有收到的请求。
Yao, what Justin request for the 1st endpoint is to get all the requests that the current user has SENT, not the requests that current user has GOT.

**Comment by GreatYYX** [comment]
@justinhe16 @maplestory06 Oops, sorry about my misunderstanding, it will be added in next update.
