### ISSUE TITLE
GET /chats/unread 这个接口返回的last_message_timestamp可以使用纯数字格式吗？

### ISSUE THREAD

**Issue by jjdddn1** [letsfae/Fae-Backend#14]
例如：20161003111510 就等于现在的2016-10-03 11:15:10
因为这种数字格式可以直接用苹果自带方法直接转换成date.不然还得手动一个一个数字截取。

不知道这个好弄不，实在不好弄的话我就手动写转换格式...

多谢！

**Comment by GreatYYX** [comment]
这个恐怕不行，虽然实现上很简单。目前所有的API接口在时间上都统一一套标准的格式(ISO 8601)，不过我们目前也没有完全符合（比如时区的问题）。后面应该还会改进，建议前端和我们一样所有时间返回调用统一的类库，保证后续的修改统一。
