### ISSUE TITLE
pinoperationcontrller里边uncomment方法

### ISSUE THREAD

**Issue by kaiqianz** [letsfae/Fae-Backend#142]
有两个delete
<img width="666" alt="screen shot 2017-07-19 at 2 21 12 pm" src="https://user-images.githubusercontent.com/16984097/28353287-9c99d9a8-6c8d-11e7-8346-e7105776d604.png">
@MrBlueberry

**Comment by MrBlueberry** [comment]
我一直用的最新的，pinoperationcontroller没有500错误，代码也没有出现两行delete，你可能拉错分支了，建议你拉最新的
