### ISSUE TITLE
[Contacts API] Requests for Search Functions

### ISSUE THREAD

**Issue by justinhe16** [letsfae/Fae-Backend#147]
Hi there! I wanted to ask for these endpoints so work on the front-end can continue:

1) A Search Function for users based upon Username
2) A Search Function for users based upon Phone Number 

Thank you so much!

cc: @maplestory06

**Comment by GreatYYX** [comment]
Sure, fuzzy search or exact match (with / without auto complete)?

**Comment by joshuayueshen** [comment]
exact match without auto complete
phone number is used for user to see if someone in his / her local contacts with phone number has already registerred as a Fae user.

**Comment by GreatYYX** [comment]
@maplestory06 since frontend needs to acquire the whole contacts in initialization, fuzzy search and auto complete should be a frontend implementation.

**Comment by GreatYYX** [comment]
@maplestory06 you mean the contacts in his / her phone (not the fae app)?

**Comment by joshuayueshen** [comment]
@GreatYYX exactly

**Comment by GreatYYX** [comment]
@maplestory06 ok, I ll add an endpoint to support it. what you need to do is to send me all the phone number list and I ll send u the id of corresponding phone number.

**Comment by joshuayueshen** [comment]
@GreatYYX thanks!

**Comment by GreatYYX** [comment]
@maplestory06 FYI, contacts search and auto complete needs to be implemented without backend.

**Comment by joshuayueshen** [comment]
@GreatYYX yes, since we have all the api to get lists of friends, data will be filterred in frontend
