### ISSUE TITLE
Wrong value of friends/request_sent

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#148]
The screenshot below is a snippet of friends/request_sent:
![image](https://user-images.githubusercontent.com/28714568/28893924-04ff845c-7788-11e7-9585-3bc4193f0153.png)

In the field "requested_user_name", "requested_user_age", "requested_user_gender", "requested_email", the values are the information of user who sent the request, rather than users who are requested.

Please check line 337 of FriendController.php, 
$requested_user = Users::where('id', $friend_request->user_id)->first(); 
Maybe it should be
$requested_user = Users::where('id', $friend_request-> requested_user_id)->first(); 

Thank you!

@maplestory06

**Comment by MrBlueberry** [comment]
已解决
