### ISSUE TITLE
[Place Pin Data Source] please help us to add more required fields

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#149]
1. open hours
2. price level （$, $$, $$$, $$$$）

**Comment by GreatYYX** [comment]
You'd better list all the possible fields you want here, re-running the crawler really takes time.

**Comment by joshuayueshen** [comment]
1. open hours
2. price level
3. image (image多多益善，但如果现有条件比较苛刻，那么还请至少来一张)
4. rate (评分)

如果可以，还请贴出来foursquare的单条数据所包含的所有字段，我们会帮忙筛选，你看这样好吗？

**Comment by GreatYYX** [comment]
rate，comment都不是店铺本身的属性，个人认为不应该做到这个里面，那些应该是根据fae的用户打分之类来决定的。我甚至觉得，图片都应该由用户来上传。

**Comment by LintaLinxi** [comment]
评分／tips／comment／review都可以不用，这个会以后我们官方来处理和自己的用户来评。照片最好能有四张左右，更多照片肯定要用户和商家自己填但是在那之前也需要有东西先在那里。

**Comment by joshuayueshen** [comment]
我这几天有用UberEat，我很好奇他们的漂亮照片是怎么拍的，而且似乎每一张照片的风格都很相似，似乎是专门请人拍的？

**Comment by joshuayueshen** [comment]
那么，1. open hours 2. price level就是目前很需要的缺少字段了
有部分地点，比如公园，没有price level，留空就行

**Comment by LintaLinxi** [comment]
好的照片肯定都是自己派摄影师去拍的，到时做专访就能拍一堆照片回来

**Comment by joshuayueshen** [comment]
I see
