### ISSUE TITLE
[Place Pin Data Source] some data is misspelled or missing class_2_icon_id

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#150]
As the issue title says.

Thx.

**Comment by GreatYYX** [comment]
@maplestory06 can you show us an example of misspelled data

**Comment by joshuayueshen** [comment]
@GreatYYX 
(when you search "&#39" in all results)

two examples:
"place_id": 62,
"name": "Budacki&#39;s Hot Dog",

"place_id": 70,
"name": "Jimmy John&#39;s",

**Comment by GreatYYX** [comment]
it's not misspelling, it's a html encoded character.

**Comment by joshuayueshen** [comment]
but should it be displayed? 

it appears 52 times in 491 results

**Comment by GreatYYX** [comment]
@SonnyYang need to convert all html encoded characters to unicode character in crawler.

**Comment by joshuayueshen** [comment]
just a reminder, some places data have no categories assigned
