### ISSUE TITLE
[Place Pin] Need "isSaved" field for every place pin data

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#151]
需要一个字段来显示这个place是否被当前用户saved

**Comment by GreatYYX** [comment]
只需要save吗 like comment之类需要吗

**Comment by joshuayueshen** [comment]
@LintaLinxi 老板，未来会需要like，comment的功能吗？需不需要后端提前开发

**Comment by GreatYYX** [comment]
我给保留吧 用不用你们自己决定 这样我接口也统一

**Comment by LintaLinxi** [comment]
Place Pin后面针对每一个place会有Ratings，Review，Tips。可以先保留后面根据具体功能再调。

**Comment by GreatYYX** [comment]
由于引入collection，这个功能和collection重叠了。以后的save需要调用collection的，save接口仍然保留，但是会和collection关联。等更新collection接口时候就可以看到了。

**Comment by joshuayueshen** [comment]
嗯 明白

**Comment by joshuayueshen** [comment]
可以做一级接口吗？就是不用打开后再查询的那种

**Comment by GreatYYX** [comment]
我现在的想法是，save不能添加save了，只能从collection添加，添加之后查询pin的时候，在pinoperations里面的save会告诉你save在了哪些collection里面，具体你要collection的信息，需要发起一次查询。因为我假设你在一级界面只需要告诉user有没有收藏，并不需要告诉他更加详细的信息，这样后端也可以减少多次join。

**Comment by joshuayueshen** [comment]
是的，只需要告诉用户是否收藏过就可以，也便于以后做筛选
