### ISSUE TITLE
[Place/Location List] New API Requested!

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#152]
POST - create a list
  	parameters:
		-list_id:
		-list_name:		   [max 60]
		-list_description:  [max 300]
		-list_owner_id: 
		-list_type:         [place/location]
		-list_private:      [Boolean]

UPDATE - edit a list by its id
	parameters:
		-list_id:
		-list_name:
		-list_description:
		-list_private:

DELETE - delete a list
	parameters:
		-list_id:
		-list_type:

POST - add an item(place/location) to a list
	parameters:
		-list_id:
		-list_type: [place/location]
		-item_id:   [the real id of place/location in backend database]
				   [place_id cannot be added to location list, vice versa]

UPDATE - edit an item in a list
	parameters:
		-list_id:
		-list_type:
		-item_id:
		-item_memo: [description of this item in this list]

DELETE - delete an item in a list
	parameters:
		-list_id:
		-list_type:
		-item_id:

GET - get a list by its id and type
	parameters:
		-list_id:
		-list_type: 		  [type can be combined to query, like 'place,location']
	responses:
		-list_name:		  
		-list_description: 
		-list_owner_id: 
		-list_type:        
		-list_private:     
		-list_created_at:
		-list_updated_at:
		-list_items:
			{
				-item_id:
				-item_memo:
				-item_added_at:
			}
			...
		
GET - get all lists of current user his/her own (no matter private or public)
	parameters:
		-user_id:
	responses:
		{
			-list_id:
			-list_type: 		  
			-list_name:		  
			-list_description: 
			-list_owner_id: 
			-list_type:        
			-list_private:     
			-list_created_at:
			-list_updated_at:
			-list_items_count:
		}
		...

GET - get all public lists of other user
	parameters:
		-user_id:
	responses:
		{
			-list_id:
			-list_type: 		  
			-list_name:		  
			-list_description: 
			-list_owner_id: 
			-list_type:        
			-list_private:     
			-list_created_at:
			-list_updated_at:
			-list_items_count:
		}
		...

**Comment by joshuayueshen** [comment]
@felixjichao @vicky66627 帮忙Review一下

**Comment by GreatYYX** [comment]
这是干嘛的？

**Comment by joshuayueshen** [comment]
给我你看几幅老板的设计图

**Comment by joshuayueshen** [comment]
![image](https://user-images.githubusercontent.com/18542103/29950061-27173fec-8e6e-11e7-9f1e-587f398d8202.png)

这幅图的意思是：点击左边那幅图的收藏button，就会弹出一个右边的那个list，用户可以选择收藏到默认的三个pin list，也可以新建一个list

**Comment by joshuayueshen** [comment]
![image](https://user-images.githubusercontent.com/18542103/29950081-592d40d0-8e6e-11e7-954c-e0e107cc0b1c.png)

这幅图是显示收藏成功以后的效果，可以看到down bottom part有undo的选项，也就是撤回刚才做的事情

**Comment by joshuayueshen** [comment]
![image](https://user-images.githubusercontent.com/18542103/29950174-da918e74-8e6e-11e7-81f0-3f56c127e792.png)

这张图，是进入某个人的某个list后出现的效果，可以看到这个list的标题，创建者，上次更新的时间，创建者给这个list的描述等等。下面的列表是这个list的items

list中有个接口显示这个list是否公开，公开的话别人就可以看见的。

整套接口的目的就是建立列表可以共享或私藏，好的list拿来共享，做攻略，导览，都是很不错的。

**Comment by joshuayueshen** [comment]
![image](https://user-images.githubusercontent.com/18542103/29950252-57eb8f1e-8e6f-11e7-8baf-60d9d05cdb0f.png)

红色框出来的地方，指的是list的作者给这个item的备注

**Comment by GreatYYX** [comment]
收藏列表啊，这个是要集成到现有的save里面的啊……这个蛋疼，结构上改动还蛮多的，让我想想怎么搞

**Comment by joshuayueshen** [comment]
麻烦啦，这个还蛮有用的。也算是日后的特色之一了

**Comment by GreatYYX** [comment]
是，这个感觉还蛮有用的。

**Comment by LintaLinxi** [comment]
Collections for Places:
Favorite Places
Saved Places
Places to Go

Collections for Locations:
Favorite Locations
Saved Locations


1，一个Place能收藏到多个list里面
2，一个memo是对于place不是list的

**Comment by vicky66627** [comment]
GET - get all lists of current user his/her own (no matter private or public)
parameters:
-user_id:
responses:
{
-list_id:
-list_type:
-list_name:
-list_description:
-list_owner_id:
-list_type:
-list_private:
-list_created_at:
-list_updated_at:
-list_items_count:
}

![image](https://user-images.githubusercontent.com/28714568/31360984-d29dcdda-ad05-11e7-9f8b-aba9622b274c.png)

这个API里没有list_items_count这个field吗？
@GreatYYX

**Comment by GreatYYX** [comment]
在 #163 中解决
