### ISSUE TITLE
[Contacts] Block之后重新加好友的逻辑

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#153]
对于Block操作，目前情况是，如果A block了 B之后，A想给B重新发送好友请求，会得到400-6的error code，同样的，B给A发送好友请求也会这样。

麻烦后端改一下：
当A(发起block操作的一方)重新向B发送好友请求时，先解除block关系，再向B成功发送好友请求。
当B(被block的一方)向A发送好友请求时，提示error code 400-6，不变。
谢谢！

@maplestory06

**Comment by GreatYYX** [comment]
这个想法没问题，但是我觉得，如果你把对方block了，然后想发起好友请求，应该显式的告诉用户“你已经把这个人屏蔽了，想加他好友就先给他松绑”，而不是毫不知情的就加了好友。 @maplestory06 怎么看

**Comment by joshuayueshen** [comment]
『你已经把这个人屏蔽了，想加他好友就先给他松绑』
这步的操作你想在当前页面做还是跑到block list里面操作？
这样的话是否以后还有一个页面要显示『已被当前用户block的用户的list』？

**Comment by GreatYYX** [comment]
微信如果你想看你block了谁，你就需要一个个进去找，这种不常用功能没必要提供list。我觉得要有侧重的做，否则所有东西都能做的很复杂啊。

**Comment by joshuayueshen** [comment]
所以直接在 重新想添加好友的时候 提示松绑，也就是DELETE BLOCK就行了？

**Comment by GreatYYX** [comment]
是的，你看这样行不行：当向自己block的用户发起friend request的时候，向后端请求后发现已经block，则提示用户已经block，unblock或者cancel，如果他选择unblock，则先unblock再发送好友请求。我觉得这个workflow会比什么都不提示直接unblock来的合理和舒服。

**Comment by joshuayueshen** [comment]
嗯 我觉得比较人性化 这样可行

**Comment by GreatYYX** [comment]
成，那这个地方就麻烦前端分两步来做。后端可以给出不同的错误代码。 @MrBlueberry

**Comment by joshuayueshen** [comment]
先等一下哈老姚，我们和老板确认一下

**Comment by joshuayueshen** [comment]
![image](https://user-images.githubusercontent.com/18542103/29958686-d2a1190c-8ea8-11e7-8254-56aa24cd4b07.png)

我在老板给的sketch里找到了block list的图 @GreatYYX

**Comment by joshuayueshen** [comment]
@GreatYYX 所以老板的意思是，只做block list，其他不做；并且，如果这个人被当前用户block了，那么get map type="user"的时候不会返回被block的数据

**Comment by GreatYYX** [comment]
OK，那相当于解除屏蔽要从屏蔽表里面做。那我就按照之前说的：对于A来说，A查询B的时候，“A屏蔽的B”和“B屏蔽的A”给出不同的错误返回码，如果两者都存在，则优先返回“A屏蔽B”。

**Comment by joshuayueshen** [comment]
@vicky66627

**Comment by vicky66627** [comment]
OK

**Comment by joshuayueshen** [comment]
@GreatYYX 如果两者都存在的这种情况老姚你都考虑到了，厉害了！

**Comment by vicky66627** [comment]
@maplestory06   根据最新issue#170, 这个issue是不是可以关闭了?因为不存在block之后前端还有可以加好友的地方。必须要先unblock，才可以重新有加好友的操作。

**Comment by joshuayueshen** [comment]
@GreatYYX @vicky66627 我觉得可以close了，看下老姚的回复吧。

**Comment by GreatYYX** [comment]
这个issue我关掉了，block和relation之间的关系都丢到 #170 吧
