### ISSUE TITLE
[Map - UserPin]判断对方和“我”的好友关系

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#154]
目前Map - userPin数据形式如下所示：
![image](https://user-images.githubusercontent.com/28714568/30040171-6e44c9c8-9190-11e7-89dd-6b0cbfecc122.png)

请问可否添加一个字段来判断当前用户和”我”的好友关系，目前应该是分为以下六种情况：
1. 我们没有任何关系  default?
2. 对方是我的好友  isFriend
3. 我向对方发送过好友请求
4. 对方向我发送过好友请求
5. 我block了对方
6. 对方block了我

这个字段  在用户进行了accept, refuse, block等操作之后直接进行修改

@maplestory06

**Comment by GreatYYX** [comment]
因为这个查询有非常多的join，比较耗资源。这些信息应该是在二级界面里的吧（而不是直接显示在地图上）？如果是，我建议的是再查询一次，我可以提供一个好友关系的查询接口。

**Comment by vicky66627** [comment]
好的，那就提供一个好友关系的查询接口吧，谢谢。

**Comment by joshuayueshen** [comment]
同意
