### ISSUE TITLE
[POST /users/account/email/verify] email verify成功后,”email_verified”值未成功更新

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#158]
![image](https://user-images.githubusercontent.com/28714568/31314135-8b076dcc-abad-11e7-8668-30be53d50d9f.png)

如上图所示，POST /users/account/email/verify该操作成功后，应更新GET /users/account 这个里面的 "email_verified"，但目前情况是verify成功后，该值依然为空 "email_verified" = "<null>";

麻烦有空看一下，谢谢。

@maplestory06

**Comment by MrBlueberry** [comment]
fixed
