### ISSUE TITLE
[Collections] array里的array问题

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#159]
![image](https://user-images.githubusercontent.com/28714568/31361599-e8641f68-ad08-11e7-9096-1ba8bb59bbc0.png)

如上图所示，get collections时，array里面还有个array，是为什么呢？

**Comment by vicky66627** [comment]
还有”created_at”里“date”的时间最后，为什么有6个0呢？ 因为数据形式不统一，前端处理起来比较麻烦。

**Comment by MrBlueberry** [comment]
fixed
