### ISSUE TITLE
GET /user/profile 获得自己的profile失败，status = 500

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#16]
如题。
以下是截图：
![image](https://cloud.githubusercontent.com/assets/18542103/19123555/ecf5533c-8ae3-11e6-87d8-45698c5e1222.png)

**Comment by joshuayueshen** [comment]
是不是要我们使用 GET /users/:user_id/profile 这个function，但这样的话不太安全对于前端来说。

**Comment by SonnyYang** [comment]
已修复，如图的截图中是获得自己的profile，所以不用加user_id。
你要活得别人的profile是要加上别人的id的，不然怎么知道获得谁的呢？而且协议中有说“获取到的字段仅包含用户设定为公开的字段”
不太理解怎么的不安全法。

**Comment by joshuayueshen** [comment]
是的，我明白，一个是get自己，一个是get别人的。
你可能误会我意思了，我以为你们会关闭这个get自己profile的接口而改用第二种方法，也就是get自己的profile需要用到自己的user_id的方法。
我说的不安全的意思是，如果我用第二种方法获得自己的profile，那么我需要获得自己的user_id，而这边会调用一个全局变量，调来调去不知道会不会出问题什么的，就是一种不确定性吧。
Anyway, 谢谢你了

**Comment by SonnyYang** [comment]
哦，你现在看一下get自己的那个能用了，就没问题了吧

**Comment by joshuayueshen** [comment]
可以了

**Comment by joshuayueshen** [comment]
谢谢!
