### ISSUE TITLE
[Collections] description字段是optional

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#160]
![image](https://user-images.githubusercontent.com/28714568/31364362-1b040522-ad19-11e7-8da0-097fe9a1ff4c.png)

老板的要求是：description字段是optional，所以即使description为空也是可以成功发送请求的。之前可能忘了说，麻烦修改一下，谢谢！

同时麻烦处理一下“create_at”里的“date”格式问题，在issue#159的评论里也有提到，谢谢！

**Comment by MrBlueberry** [comment]
fixed

**Comment by vicky66627** [comment]
@MrBlueberry  麻烦check一下，是服务器没有更新吗 
![image](https://user-images.githubusercontent.com/28714568/31574141-44b807de-b07e-11e7-830e-104c7c74d53f.png)

**Comment by MrBlueberry** [comment]
代码没问题， @SonnyYang 更新没
