### ISSUE TITLE
[Collections] default collections

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#161]
老板对collection的要求：when user create account, we default create 3 lists in places and 2 lists in locations
这三个places的名字从1到3分别是：Favorite Places, Saved Places, Places to Go
两个locations的名字从1到2分别是：Favorite Locations, Saved Locations
这几个默认的collections可以任意修改和删除

![image](https://user-images.githubusercontent.com/28714568/31365963-7294c862-ad23-11e7-8518-24a7e82a8880.png)
![image](https://user-images.githubusercontent.com/28714568/31365967-7c0e1c4a-ad23-11e7-8e23-2cdc6ee1c5ea.png)

@maplestory06

**Comment by GreatYYX** [comment]
OK, 这个可能 @MrBlueberry 忘了加了，会在创建新用户的时候加入。

**Comment by MrBlueberry** [comment]
fixed
