### ISSUE TITLE
[Phone] 更新电话号码和帐号一一对应

### ISSUE THREAD

**Issue by felixjichao** [letsfae/Fae-Backend#162]
GET /existence/phone/_batch 现在的状态是"phone并不惟一，即会有重复"，
更新为帐号与电话号码一一对应。
当已经绑定的电话号码被请求与新帐号绑定时，需要将该电话号码与旧帐号解绑，再与新帐号绑定，以防电话号码更换主人。

**Comment by GreatYYX** [comment]
phone登记时候也需要唯一 @MrBlueberry

**Comment by GreatYYX** [comment]
加入phone的用户与当前用户的关系：无关系，互为好友，我发送过请求，对方向我发送过，我block过对方，对方block过我。

**Comment by GreatYYX** [comment]
需要加入解除phone绑定的接口
