### ISSUE TITLE
[Collections] GET /collections, item_count字段缺失

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#163]
@MrBlueberry 

在返回所有当前用户的collections的接口中，缺少：

1. 每个collection的item数目item_count
2. 该collection的创建者creator_id
3. updated_at

还麻烦尽快修复！

谢谢了！

@vicky66627

**Comment by joshuayueshen** [comment]
![28171508187052_ pic](https://user-images.githubusercontent.com/18542103/31649264-d6f892c2-b2c6-11e7-8e75-a8dec63a3116.jpg)

**Comment by GreatYYX** [comment]
updated at

**Comment by GreatYYX** [comment]
@maplestory06 其实item count不用给你的，你获取collection对象之后len(pins array)即可。

**Comment by joshuayueshen** [comment]
@GreatYYX 需要item_count
1. 这个接口是获取所有的collections（复数），然而在这个层级，并不能获取所有的collection的内部信息
2. 我们的设计图里，在获取所有的collections的界面中，需要显示每个collection对应的item数目
附图

**Comment by joshuayueshen** [comment]
![image](https://user-images.githubusercontent.com/18542103/31791090-65854e16-b4cc-11e7-9aed-1a7629399c9b.png)

**Comment by GreatYYX** [comment]
ok
