### ISSUE TITLE
[Collections] GET 获取单个collection时需要的额外信息

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#165]
@MrBlueberry 

获取单个collection时需要的额外信息，
目前返回的pin_id仅仅是pin_id，缺少：

1. pin: the time that pin added to collection
2. collection updated time: update of collection, and the last pin added to this collection

麻烦改进一下，谢谢！

@vicky66627

**Comment by joshuayueshen** [comment]
![image](https://user-images.githubusercontent.com/18542103/31649529-255c892c-b2c8-11e7-8606-ae14cfdf3ea2.png)

**Comment by GreatYYX** [comment]
pin: the time that pin added to collection
collection updated time: update of collection, and the last pin added to this collection
