### ISSUE TITLE
[Contacts] Block关系

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#170]
![image](https://user-images.githubusercontent.com/28714568/32312893-5da16fe0-bf5d-11e7-92f8-7ada1e64477d.png)
经过和老板的讨论，确定需要麻烦后端实现的block关系如下：
1. 无论用户之间是什么关系，都可以进行block操作。
2. 在block之前是好友关系，即is_friend为true，block之后双方依然存在于对方的friend list中，is_friend依然为true。被block的一方出现在block那方的block list中。
3. 在block之前是非好友关系，即friend_requested或friend_requested_by为true，或二者不存在关系，解除request关系（request关系变为false，双方的request或request_sent列表里不再有对方）。被block的一方出现在block那方的block list中。

@maplestory06

**Comment by vicky66627** [comment]
@GreatYYX 所以现在可以得到blocked list吗？

**Comment by GreatYYX** [comment]
不可以哎 你需要block的总表？ @vicky66627

**Comment by vicky66627** [comment]
![image](https://user-images.githubusercontent.com/28714568/33236122-ab2ae3fa-d1fe-11e7-9a1b-cf72beea4ddb.png)
对的，前端有一个这样的页面。需要像获取friend list那样得到blocked list。 @GreatYYX

**Comment by GreatYYX** [comment]
@vicky66627 ok, will be added soon
