### ISSUE TITLE
【reset_login】添加phone的验证

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#171]
POST reset_login/code
POST reset_login/code/verify
POST reset_login/password
这三个接口目前只支持email的reset，麻烦加上phone的验证。谢谢！

@maplestory06

**Comment by GreatYYX** [comment]
这个地方我们已经在实现了，但是出现一个问题：
1. 如果A用户原来持有手机号N，之后放弃该手机号。
2. B持有了N，之后B在没有注册情况下（注意此处B没有注册为fae用户）直接通过N重置登陆密码，此后B可以直接套用A的账户登陆。


*. 根据目前的逻辑，如果B注册了用户并绑定手机号，则N属于B，不会出现上述问题，但是问题就在于如果B不注册，则可以直接冒名顶替A。

总结，我觉得手机号不能作为密码重置和登陆的唯一凭证（虽然它也是唯一的），否则就需要解决这个问题。但是手机号可以作为dual verification的一步，比如用户希望更加安全的登陆或者异地登陆，此时需要在正常user/pass验证之后再进行一步phone的验证。 @maplestory06

**Comment by joshuayueshen** [comment]
前端这边设计的逻辑是：要通过phone或email重置登录密码，就必须知道绑定该phone或者email的username是什么，所以，输入phone或email之前，要先输入username，并且username必须和phone或email是绑定的。 @vicky66627 @felixjichao @GreatYYX

**Comment by GreatYYX** [comment]
great! 那就不会有问题 后端得加入username @MrBlueberry

**Comment by joshuayueshen** [comment]
reopened this issue on the demand from @felixjichao

**Comment by felixjichao** [comment]
@GreatYYX 
email存在的时候 不需要username字段

**Comment by GreatYYX** [comment]
@SonnyYang 经过讨论 reset_login中，phone和username需要一起出现，email只需要单独出现
