### ISSUE TITLE
去掉 邮箱/电话 更新/验证 接口的auth

### ISSUE THREAD

**Issue by felixjichao** [letsfae/Fae-Backend#172]
POST /users/account/email
POST /users/account/email/verify
POST /users/account/phone
POST /users/account/phone/verify

因为现在新的注册流程中需要用户必须验证email或者phone，所以需要取消这些接口需要auth的限制。

**Comment by joshuayueshen** [comment]
@GreatYYX

**Comment by GreatYYX** [comment]
这个不太合理，我大致和你们在这儿解释一下，如果没看懂或者还需要进一步解释，我和你们电话说。

首先说开放这4个接口的弊端：
没有auth情况下，相当于只要知道协议（中间人攻击后猜解等），就可以重置任意用户的邮箱或者电话。

因此需要有一种中间状态证明用户是合法的。
最简单的方案是注册时候一次性提供所有的信息（signup是不用auth的），但是email和phone的验证是两次单独接口调用（第二个和第四个接口），所以没有办法做到一个请求完成所有的事情。
所以正确的做法应该是，用一种中间状态，或者说就是用户登陆状态解决这个问题。后端认为的正确的登陆流程应该是：
（无论前端界面上如何交互，）用户填写用户名、密码、email等必要信息，之后前端就应该让用户登陆（因为有用户名和密码），但是这个登陆可以是不显示给用户的（即用这个登陆进入中间状态），之后调用第2接口完成email验证，再用3、4完成phone的登记和验证。注册和验证完整的完成后，前端此时可以决定是否显示给用户已经登陆的状态（对于用户来说就是注册成功后就自动登陆了），或者退出并让用户重新登陆（我偏向前面那个方案）。
该方案可能存在的问题是，用户注册了一半（即signup接口完成），但是没有进行验证，此时用户不能再注册（因为用户已经存在了）。但是在登陆的时候前端发现email和phone没有验证，可以要求强制验证（这根据你们的需求来），这样才是一个比较合理的注册和验证流程。
如果用户注册完没有验证就忘记密码了（但是注意我们email是signup必填的），此时可以直接reset_login。后端接口这样设计是为了满足基本的安全性，同时最大的弹性（即你们需求变更后依然可以用现在的接口组合来实现）。

**Comment by GreatYYX** [comment]
还有需要注意email和phone的区别，对于后端来说，email是必须的，phone不是，email注册时候就有，没有验证也可以存在，phone在没有验证的情况下是不会保存到后端的（为了解决phone归属于谁的那个逻辑问题）。

**Comment by felixjichao** [comment]
@GreatYYX 参考了一下snapchat的注册流程
在用户输入完name, birthday, username, password之后就完成用户注册
然后强制用户phone/email验证一个
当进入验证界面后，用户就不能再返回去修改注册信息。
如果这个时候用户放弃验证，那么下次用户用这个username登录时就直接跳转到验证界面

1. 把email从sign up的字段中拿掉
2. 在sign up的时候返回auth信息（避免调用log in再次发送请求）

这样的改动是否可行？

**Comment by GreatYYX** [comment]
但是这样的问题在于前后端绑的太死。如果前端并不想这样做，注册后登陆就很不合理了。
为了满足目前端的注册需求，可以用“自动后台登陆”来模拟中间状态。但是这种状态不是必须的，可以是没有的，所以后端觉得需要前端发起一次请求的好。何况这样前端也就是加个request而已啊。
关于email，当时的要求是required，这个需求改了？如果email不是必须的，那我可以看看后端怎么改一下，应该是有一点改动的。

**Comment by joshuayueshen** [comment]
是的，这个需求改了，我们目前的机制是完全模仿现有的比较成熟的社交app的设计模式

**Comment by joshuayueshen** [comment]
按照我们的设计，如果一个账户没有验证email或者phone，（必须验证其中一个，this is required）

**Comment by felixjichao** [comment]
注册流程中增加 email 项，但是验证的时候可以选择email或者phone
