### ISSUE TITLE
错误返回码文档

### ISSUE THREAD

**Issue by GreatYYX** [letsfae/Fae-Backend#173]
除了全局文档( https://github.com/letsfae/FaeMap-Backend/blob/master/docs_zh_cn/protocol_error_code.md )外，针对每个接口，更新相应的文档。

**Comment by GreatYYX** [comment]
@maplestory06: @MrBlueberry 已经更新了一部分文档了，目前还在dev上，https://github.com/letsfae/FaeMap-Backend/blob/dev/docs_zh_cn/protocol_chats.md

**Comment by joshuayueshen** [comment]
请问一下现在文档更新情况？ @GreatYYX

**Comment by MrBlueberry** [comment]
目前除了USER 和 PIN两个API文档其余的更新完了
