### ISSUE TITLE
[证书问题] 详情见issue里detail

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#179]
问题是这样，有一台手机登录不了app，其他所有人的都可以。

这台手机在登录界面登录的时候，debug信息如下：

▿ [Request]: POST https://dev.letsfae.com/authentication
[Response]: nil
[Data]: 0 bytes
[Result]: FAILURE: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9800, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x1c8051ee0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9800, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9800}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://dev.letsfae.com/authentication, NSErrorFailingURLStringKey=https://dev.letsfae.com/authentication, _kCFStreamErrorDomainKey=3}
[Timeline]: Timeline: { "Request Start Time": 539289333.196, "Initial Response Time": 539289333.279, "Request Completed Time": 539289333.279, "Serialization Completed Time": 539289333.279, "Latency": 0.083 secs, "Request Duration": 0.083 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.083 secs }
  ▿ request : Optional<URLRequest>
    ▿ some : https://dev.letsfae.com/authentication
      ▿ url : Optional<URL>
        ▿ some : https://dev.letsfae.com/authentication
      - cachePolicy : 0
      - timeoutInterval : 60.0
      - mainDocumentURL : nil
      - networkServiceType : __ObjC.NSURLRequest.NetworkServiceType
      - allowsCellularAccess : true
      ▿ httpMethod : Optional<String>
        - some : "POST"
      ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
        ▿ some : 5 elements
          ▿ 0 : 2 elements
            - key : "Content-Type"
            - value : "application/x-www-form-urlencoded"
          ▿ 1 : 2 elements
            - key : "Device-ID"
            - value : "a5e0491a7c38dc127dc4b5cccf53a4deb4c18f960567716dd5c975f5b6ca941c"
          ▿ 2 : 2 elements
            - key : "Accept"
            - value : "application/x.faeapp.v1+json"
          ▿ 3 : 2 elements
            - key : "User-Agent"
            - value : "iPhone10,3 11.2.1"
          ▿ 4 : 2 elements
            - key : "Fae-Client-Version"
            - value : "fae-ios-1.0.0"
      ▿ httpBody : Optional<Data>
        ▿ some : 124 bytes
          - count : 124
          ▿ pointer : 0x00000001c410dae0
            - pointerValue : 7584406240
      - httpBodyStream : nil
      - httpShouldHandleCookies : true
      - httpShouldUsePipelining : false
  - response : nil
  ▿ data : Optional<Data>
    ▿ some : 0 bytes
      - count : 0
      ▿ pointer : 0x00000001c4005910
        - pointerValue : 7583324432
      - bytes : 0 elements
  ▿ result : FAILURE: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9800, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x1c8051ee0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9800, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9800}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://dev.letsfae.com/authentication, NSErrorFailingURLStringKey=https://dev.letsfae.com/authentication, _kCFStreamErrorDomainKey=3}
  ▿ timeline : Timeline: { "Request Start Time": 539289333.196, "Initial Response Time": 539289333.279, "Request Completed Time": 539289333.279, "Serialization Completed Time": 539289333.279, "Latency": 0.083 secs, "Request Duration": 0.083 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.083 secs }
    - requestStartTime : 539289333.19624197
    - initialResponseTime : 539289333.27928197
    - requestCompletedTime : 539289333.27928197
    - serializationCompletedTime : 539289333.27948797
    - latency : 0.083039999008178711
    - requestDuration : 0.083039999008178711
    - serializationDuration : 0.00020599365234375
    - totalDuration : 0.083245992660522461
  ▿ _metrics : Optional<AnyObject>

@SonnyYang @GreatYYX

**Comment by joshuayueshen** [comment]
这里面的关键句应该是：

"An SSL error has occurred and a secure connection to the server cannot be made."

**Comment by joshuayueshen** [comment]
this link may be a solution

https://community.letsencrypt.org/t/an-ssl-error-has-occurred-and-a-secure-connection-to-the-server-cannot-be-made/49013

**Comment by SonnyYang** [comment]
我把证书又重新修正了一遍，你们看看有没有用。

我网上查的大部分的-9800的错误都是tls混乱，我暂时现在禁用了1.0,1.3等其他，只允许1.2，看看有没有效果，还有会不会影响其他设备。

不行我就改回去，尝试一下其他方法

**Comment by joshuayueshen** [comment]
谢谢！
