### ISSUE TITLE
front-end requirement 20161008

### ISSUE THREAD

**Issue by GreatYYX** [letsfae/Fae-Backend#18]
d 1. media 6 pics
d 2. namecard save, saved namecard list
d 3. report (pin, namecard) *
d 4. pin: duration (other 3h, chatroom 1d), interaction radius(1km)
d 5. chat timestamp desc
6. chat pin: room capacity: 50, tag
d 7. invisible
8. push notification *
d 9. pin read / unread
d 10. up vote, down vote of pin's comment
n 11. activity: like, save, comment (edit / delete), reply (edit / delete)
t 12. guest account (privilege)
13. search: text, [tag], hashtag, distance, saved, read / unread
d 14. pin, comment, reply in anonymous
15. tag helper

**Comment by jjdddn1** [comment]
希望能再增加一个接口，用于返回当前用户所有未读Chat的总数。
比如说： GET /chats/unread/total这种感觉。
然后里面需要: user_id, unread_count_total, server_send_time. 这样

因为我觉得以后聊天人数多了，如果使用 
GET /chats/unread + GET /chat_rooms/message/unread
返回的文件可能比较大，然后拿到以后还要统计全部未读信息总数效率感觉很低。可能靠服务器来做会快很多。

用途是地图界面左下角聊天图标的那个未读统计。

**Comment by GreatYYX** [comment]
@jjdddn1 (sorry, I don't have Chinese IME on current computer) you can use `sync` instead, don't forget it
