### ISSUE TITLE
POST /friends/accept 500错误

### ISSUE THREAD

**Issue by felixjichao** [letsfae/Fae-Backend#188]
接受好友请求时，返回错误

Unable to connect: tls://gateway.sandbox.push.apple.com:2195: 2 (stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error)

**Comment by vicky66627** [comment]
send friend request时也有这种情况，返回的status code是500，但实际上已经成功发送了好友请求。

**Comment by SonnyYang** [comment]
暂时关闭了apns的功能，借口正常运行了
