### ISSUE TITLE
[Contacts] POST /friends/request ErrorCode

### ISSUE THREAD

**Issue by vicky66627** [letsfae/Fae-Backend#189]
POST /friends/request
400-22 | 对方给你发送过好友请求

此处，当A已经向B发送了好友请求，B在没有接收的时候（或者说因为时间差，B并不知道A向他发送了好友请求）再向A发送好友请求。是不是应该直接让A, B成为好友（因为互相都有请求成为好友的操作），而不是报错说“对方给你发送过好友请求”？

当然前端的设计会尽量避免这种情况的出现，但从逻辑上来说，是否应该取消400-22这种情况的发生？

@GreatYYX @maplestory06

**Comment by joshuayueshen** [comment]
@GreatYYX plz response, 问题已经提出一周了，still no response yet.

**Comment by SonnyYang** [comment]
当初接口设置的时候考虑过这种情况。

B再重复向A发送请求时，如果直接成为好友，并没有通知A，当初讨论这种不太合理，和前端商量过这种情况。

当初的解决方案是，前端sync，用户先解决现有的request，再发送新的请求
