### ISSUE TITLE
如何知道一个用户是否Like了一个Pin？

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#2]
从协议上看，现在可以用comment_id获取pin_attribute, 里面有likes的数目，但是貌似不知道哪些用户like这个pin。现在要实现的是，load comment pin的detail view里，如果当前用户给这条pin点赞了，那么点赞的心💖是hollow，是被镂空的，otherwise, 是被填充的。

**Comment by GreatYYX** [comment]
恩，这个问题已经注意到了，目前提供的方案是，单独获取该用户对于所有pin的操作（listA），之后对比当前pin是否在listA中，这个方案前端负担比较重。我们下周会上线对于该API的1级冗余，所有pin节点中（目前为get comment pin, get user comment pins, get media pin, get user media pins）都会含有is_liked和is_saved关键字，但是对于pin的comment，依然需要通过单独接口获取。

类似于这样

```
{
    ...,
    "user_pin_operations": {
        "is_liked": @boolean, 对当前用户是否点赞
        "liked_timestamp" @string,
        "is_saved": @boolean 对当前用户是否收藏
        "saved_timestamp" @string,
    }
}
```
