### ISSUE TITLE
login部分服务器返回的信息有一点乱

### ISSUE THREAD

**Issue by jjdddn1** [letsfae/Fae-Backend#27]
用户名：jkslfjslkjsdkffjd（随便的一串）
密码：sufisduif(随便的一串)

这时候服务器返回的信息是不是应该是用户名不存在？
而现在返回的好像是: Please verify your information

前端这边很难判断究竟是出现了什么问题...

**Comment by GreatYYX** [comment]
...这个问题是（摊手） 我当时说所有错误定义返回错误码（就是error_code） 但是前端和我说不要 只要返回错误就行 所以我们就只能返回错误大类（HTTP status code级别的）

**Comment by jjdddn1** [comment]
这...这...这...这...这我该如何是好...(手动懵逼)

**Comment by GreatYYX** [comment]
当时我反复确认过。。。当时前端的反馈是 只要不是正确的 直接返回字符串形式的错误信息 然后直接显示在UI上。作为历史遗留问题 如果要修正我最近可以让后端制订下返回码 不过工程量浩大

**Comment by GreatYYX** [comment]
目前考虑加入错误码 但是会逐个增加逐渐放出来
