### ISSUE TITLE
Comments of Pins have "like" and "dislike" functions, can it be implemented ASAP?

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#32]
根据最新UI设计，
取消了vote和devote pin的功能，仅仅保留like和unlike（不是dislike）的功能。
pin的comments取消like和unlike的功能，保留了"like"和"dislike"（不是unlike）的功能，
后端可以提供相关的接口给pin的comments的like和dislike吗？

**Comment by GreatYYX** [comment]
这个问题没法很快实现，我把新接口放到我的schedule里面了，因为涉及到创建新表、原来的表插入新字段、新接口、老接口更新等一堆问题。而且，本周的任务已经下去了，这个可能没法在这周做了。
