### ISSUE TITLE
Pin - "created_at" is incorrect, and not in right timezone

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#33]
Pin的创建时间有一定误差，不是因为时区误差，比如现在是1:30pm，那么我的pin的创建时间会显示1:28pm, 另外时区问题有什么方法解决？在后端解决还是前端解决？

**Comment by GreatYYX** [comment]
创建时间误差应该是服务器时间校准的问题。
时区问题是前端自己算的，后端时间是UTC时间。

**Comment by joshuayueshen** [comment]
好的
