### ISSUE TITLE
GET /map type="user", 可否在返回的JSON字段加入user的miniavatar字段？

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#35]
目前显示地图上的user的同时，
需要用user_id获取user的mini_avatar，一个请求中包含n个mini_avatar的请求。
感觉很不方便，代码也很乱，不知道后端这边是否可以enhance一下？

如果不行还行说明一下原因哈

Thanks in advance!

**Comment by GreatYYX** [comment]
received! it will be added soon.

**Comment by joshuayueshen** [comment]
awesome!

GreatYYX notifications@github.com于2016年11月19日 周六10:17写道：
