### ISSUE TITLE
File: About Media

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#42]
目前get的图片都是挺大的，这个挺考验网速。

所以我们前端的想法是，在获取图片的时候先得到图片或视频的缩略图，一个小文件。

点开缩略图后，显示完整大图，就像微信朋友圈那样。

希望后端可以在我们上传大图片后压缩一下，生成一个小图片，我们前端可以先get小图片，如果用户需要，再获取大图片

**Comment by GreatYYX** [comment]
这个建议我最近会提上日程，但是由于采用了统一了文件接口，方案具体怎么落实我还要考虑下。
