### ISSUE TITLE
Pin Operation: Cannot Delete Pin with pin_id, status code == 500 [bug]

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#47]
@SonnyYang @GreatYYX

**Comment by joshuayueshen** [comment]
好像可以delete但是返回的status code有问题

**Comment by MrBlueberry** [comment]
能描述的具体一点？那个URL，什么参数？

**Comment by joshuayueshen** [comment]
@MrBlueberry 
media pin没问题，但comment不行
![image](https://cloud.githubusercontent.com/assets/18542103/20937813/653f9eee-bb9d-11e6-8955-ad23db1b5d3d.png)

**Comment by MrBlueberry** [comment]
已解决，会尽快更新服务器的
