### ISSUE TITLE
getMap中in_duration的格式应该是boolean

### ISSUE THREAD

**Issue by kaiqianz** [letsfae/Fae-Backend#48]
in_duration格式应该是boolean，但是我测试输入string的格式才能合格。你应该改一下getmap，使得为boolean输入格式。
<img width="814" alt="screen shot 2016-12-06 at 3 35 51 pm" src="https://cloud.githubusercontent.com/assets/16984097/20948593/b23b827c-bbc9-11e6-882d-6aab6a0d2a57.png">

**Comment by MrBlueberry** [comment]
输入是string啊，你看清楚validation。。。

**Comment by kaiqianz** [comment]
你看协议输入是boolean

**Comment by kaiqianz** [comment]
你的测试用string的形式才能成功

**Comment by MrBlueberry** [comment]
.........是String， boolean laravel没法过的，这个不用说了，你用string就行
