### ISSUE TITLE
需要更新Create Chat_room 的api

### ISSUE THREAD

**Issue by jjdddn1** [letsfae/Fae-Backend#49]
目前已有的：
title	string(100)	聊天室名
geo_latitude	number	纬度
geo_longitude	number	经度
duration	number	持续显示时间，前端需默认为1440,单位为min
interaction_radius (optional)

根据老板的设计， 还需要增加：
file_id(optional)   就1个， 其实这个就是Chatroom的简介图片这样子...
tag_ids (optional)	tag_id	最多50个，通过;区分
description (optional)
room_capacity (optional)
这几个。 跟media pin差不多

以后可能还会增加...

**Comment by GreatYYX** [comment]
收到！
但是不是很清楚简介图片的意思，能否给个贴图；如果是特殊情况，可能需要和avatar一样独立接口而不是共用file接口。

**Comment by GreatYYX** [comment]
@jjdddn1 这里的room capacity是指用户可以自己设定room的大小？有没有上限？

**Comment by jjdddn1** [comment]
用户可以自己设置。我觉得要不这样，范围就先弄成 2-200。如果用户没有提供这项的话就默认50.

**Comment by GreatYYX** [comment]
cover image我就和namecard及avatar一样提供单独的接口，因为是唯一的，就不采用通用的file接口了。

**Comment by jjdddn1** [comment]
OK，多谢。 我看到Readme里面更新了，是不是这些改动已经传到Dev和Api服务器上了？

**Comment by GreatYYX** [comment]
还没有，抱歉。因为我现在文档只有一个版本，所以新任务和完成的任务写在了一起，这是后端下周的任务，我们更新以后会告诉你们。你们可以先以之前的commit里面的为准。
我是在考虑文档也分一个单独的分支出来，这样好维护。

**Comment by jjdddn1** [comment]
了解！
