### ISSUE TITLE
Profile Avatar: 设置字段来表征本地头像是否和云端匹配

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#50]
获取头像是个费力活，网络不好的时候获取头像很占用网络资源。

所以前端想是否可以用image hash出一个简易字段配合这个image所属的user_id，用来compare本地的字段，如果二者一样，则不进行下载image的操作，如果不一样，则可下载。

目前，file_id可以用来做这个工作，我本地以file_id为主primary key建立了一个class，file_id在本地存在，那么则不用再次下载这些file。但avatar以及cover image似乎没有这个功能？因为不是用file_id来存的？

麻烦诸位了。

**Comment by GreatYYX** [comment]
avatar和cover image对于用户是唯一的，所以不需要这些。你如果需要一个PK，可以使用user_id，如果你需要区别avatar和cover image，可以自定义key，如avatar_{user_id}, cover_{user_id}。

**Comment by joshuayueshen** [comment]
对，是唯一，但如果用户更改了avatar或者cover，那么如何判断这个"唯一"被改变了呢？

**Comment by GreatYYX** [comment]
我决定采用HTTP标准的ETAG来制定缓存方案。实现后请参考协议来落实具体流程。
