### ISSUE TITLE
关于预留一部分User_id以及各种官方账号以及用户注册后给用户发欢迎信息

### ISSUE THREAD

**Issue by jjdddn1** [letsfae/Fae-Backend#51]
我的想法是这样...

我们服务器**保留一定的User_id**，私用，比如说1-99。正常注册的用户user_id从100开始。
因为我们需要有一些**官方账号**，比如说老板设计里面有一个“Fae Map Crew”。这个账号在每个用户注册以后都会给用户发一段欢迎信息：

“_Hey there! Welcome to Fae Map! Super happy to see you here. We’re here to
enhance your experience on Fae Map and make your time more fun. Let us know of any problems you encounter or what we can do to make your experience better. We’ll be hitting you up with
surprises, recommendations, favorite places, cool deals, and tons of fun stuff.
Feel free to chat with us here anytime about anything. Let’s Fae!_ ” 

这个功能就需要后端来实现一下, 每有一个新用户创建成功，就给该用户推送这个消息，同时更新最近聊天列表。我会在前端更新fireBase，把这条消息加入一个chatroom, 来“假装”服务器发送了这条消息给用户。（因为我没查到怎么通过后端直接更新firebase...如果有办法请告诉我，我再研究一下...）

总之，目前来讲的需求就是这样：
1. 希望后端能预留出一部分user_id官用(1-99)
2. 不知道能不能从后端直接创建出user_id = 1(暂定)，user_name = "Fae Map Crew"的用户，未来可能会需要后端创建更多的官方账号
3. 需要在用户创建账号后，通过“FAE Map Crew”账号给用户账号发一条消息，内容在上面。

说得有点乱不知道你们能不能看懂...麻烦啦！

**Comment by GreatYYX** [comment]
收到！我可以让后端实现直接创建系统账户的问题。至于向用户发送的第一条消息，可能需要前端实现。理论上说firebase应该是被后端调用的（这是个历史遗留问题，我最早的架构雏形中后端是唯一的，所有三方接口也由后端来调用，可是最后……），但是根据目前情况，firebase最好全部由前端调用（否则后端一旦参与反而就乱掉了）。

**Comment by GreatYYX** [comment]
至于前端如何记忆第一条消息是否发送的办法，我觉得是一开始检索下这个crew账号是否有过数据，没有的话直接创建一条。（这个功能其实却是应该后端来做，就比如目前twilio啊apns啊之后都是后端在调用，对于前段只有后端一套api，这个角度来说，最初我的想法应该是对的……）
