### ISSUE TITLE
（加急）🔥 get map: 返回值添加 🔥

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#52]
麻烦在get map, (pin, not user)的时候针对每条添加多一些返回值以供前端实现pin_state。

目前有四种pin_state: 
1. Normal(一般，其它三种都不成立，那么就是这种)
2. Read(已读)
3. Hot(Pin的评论数目大于等于10，或者赞的数目大于等于15，满足其中之一即可)
4. New(based on "created_at"这个字段，十五分钟内发布的pin都会显示new)

注意：
a. Read和New不会同时存在，如果用户A对这个new pin执行了read的操作的话，那么这个pin对于用户A就不是new pin而是read pin了，new pin变成normal pin的条件是new pin过了十五分钟。
b. hot pin的优先权永远大于new pin，hot和new不会同时存在，如果一个new pin在十五分钟之内达到了hot pin的条件，那么这个pin的pin_state自动变成hot pin

后端在服务器上可否帮我们判断这四种状态然后返回，在前端处理过于浪费资源。
@GreatYYX

**Comment by GreatYYX** [comment]
已读和未读已经有pin级别的接口了，这周后端也加入到get map接口中（任务已经下去了）。我个人不建议把状态判断放在后端，因为感觉这些判定规则完全就是按照UI在改变，不应该属于数据层的范畴。

具体属于数据还是属于功能，我的判断是：如果置换了前端，实现这些数据是否是必须的（有点像范式）。比如如果有个新的前端引入，但是判定规则不是这样的，那它可以直接通过现有的数据实现而不需要再次改变接口，这才能做到一套通用接口。所以除非是数据或者是必须后端做的逻辑实现（比如filter啊、设定文件关联啊之类的），其他都需要延迟到前端做。
不过从做轻客户端的角度说，你的想法没错，但是我个人建议现在先不这样（现在尽量做最保险的前后端完全分离），何况老板那边细节需求依然不定，后端做的话更新时候前后端都要更新，而前端做则不涉及后端更新。

**Comment by joshuayueshen** [comment]
先给你描述一下目的和具体的case，可能会更好帮助理解一些。
目的：
    减轻网路请求次数，减轻前后端压力
case: 
    pin的已读未读，hot，new，normal的显示是直接显示在用户界面的地图上的，也就是说，用户直接看地图就可以知道这个pin的state而不用打开这个pin。打开地图点击某个pin to get its detail information我们用后端提供的接口，get media info by media id，get comment info by comment id，但是很多具体的东西，例如："created_at", "likes_count", "saves_count"都是用pin_id来get的，但是get map这个接口目前还不能直接完成pin state的计算，在调用get map以后，前端得在这个get map操作里执行第二层操作就是get pin by pin_id，以此来计算这个pin_state，最终这个可以呈现在map上。如果从网络请求的复杂度上来说，（不知道可不可以这么讲），获取一次get map调用一次就好，但里面包含N个pin，那么我就得而外做N次的网络请求。

**Comment by joshuayueshen** [comment]
如果能把以下几个已有的pin的参数在get map这个接口里和"created_at"同级，那么我们会非常感激的。
1. pin_likes_count [Int]
2. pin_comments_count [Int]
3. created_at (已经有)
4. pin_is_read_by_user [Bool]
这几个其实你们是可以加入的，对吗？这样的话，就不用后端来判断pin_state了，前端可以做。不知道这样是否可以？
@GreatYYX

**Comment by GreatYYX** [comment]
好的 这些会加入的
