### ISSUE TITLE
需要更新POST /chats 里面的Type类型

### ISSUE THREAD

**Issue by jjdddn1** [letsfae/Fae-Backend#55]
现有的是：'text','image','sticker','location','audio‘， 希望能把image改为:'picture'，这样比较好统一。
另外需要增加:'video'和'gif'，以及一个比较特殊的类型'heartSticker'。

这个heartSticker的概念可以看下这个gif
https://www.dropbox.com/s/hnay2ylm2e7k7x8/heart_button.gif?dl=0

大致的意思就是有一个快捷键可以直接发送一个💖出去。
然后具体要求来了...如果从我(HuiyuanRen)这边发送一个heart给对方，那么我这边的最近聊天需要更新成: "you sent a heart", 而对方的最近聊天需要更新成: "HuiyuanRen sent a heart". 而对方收到的推送则显示成:"HuiyuanRen: sent a heart"。由于显示的信息不同，我觉得这个只能后端处理一下了....

然后关于这个heart, 我感觉也可以不添加一个新的"heartSticker"类型，我把它当成'sticker'来处理，然后在message里面提供"[heartSticker]"，然后后端只要检测到message == "[heartSticker]" && type == "sticker",就做上述处理...

或者有啥更好的方法也请告诉我，多谢啦！

**Comment by GreatYYX** [comment]
如果用富文本，就可以引入自定义标签，这个我需要和后端核对一下。不过我觉得，其实我可以再聊天里面给你单开一种类型叫customize，然后里面所有的标签（内容）你自己来定义，这样如果是这种类型的，前端也可以全全控制，也不用等后端更新了，方便很多。

**Comment by GreatYYX** [comment]
对了，关于image这个字段，如果你不介意的话能不能继续用image，因为后端对于图片出现的地方都统一叫image了……（除了avatar，name_card_cover，name_card_photo）

**Comment by jjdddn1** [comment]
那就继续用image 吧~

**Comment by jjdddn1** [comment]
也就是说用customize类型，我可以自己定义我和对方看到的最近聊天信息？这样确实方便很多啊

**Comment by GreatYYX** [comment]
@jjdddn1 目前后端并不处理message的内容（可能以后会参与处理），type也是为了前端使用的。前端可以根据type来确定message是什么。考虑到可能有些type并不是通用的，所以我就指定一种customize类型，这样这种类型的message内容前端可以视为由前端全权接管的（这是和其他type最大的区别），后端完全不处理。

给你几个例子：

```
type: customize
message: [heartsticker]
```
那这就是个“心”的标记。

```
type: customize
message: <a href="http://example.com">XXXXXX</a>
```
一个html超链接。
