### ISSUE TITLE
关于GET /chat_rooms接口相关

### ISSUE THREAD

**Issue by jjdddn1** [letsfae/Fae-Backend#56]
首先这个GET /chat_rooms似乎还不能用...
然后，不知道能不能把这个和GET /chats合并为一个？因为每次更新最近聊天都要Get两次然后再合并再重新排序似乎太耗时了。
能不能直接把这两个返回结果放到一个接口里，然后我可以通过判断是否含chat_id/chat_room_id来判断类型。同样需要排序。
多谢啦！

**Comment by GreatYYX** [comment]
后端貌似他们有事还没推送更新。接口合并是要做的，不过chat和chatroom返回结构不同，我会给你一个字段判断是什么类型。

**Comment by GreatYYX** [comment]
不过这个接口合并可能需要一段时间，原因还是因为目前对于群聊和私聊使用两套完全不同的接口和数据表。如果需要将两者合并并排序，后端需要加入辅助表（就和map和pin的关系一样），这个改起来比较麻烦。另一个方案就是我之前和你说的完全整合chat和chatrooms，把所有的聊天都视为chatroom，但是这样做的风险就是老板的方案必须是两者可以调和的而不是功能完全不同的，否则整合之后后期的修改代价就非常大。我目前建议先保留调用两次的方案，等我和老板确认以后再修改这部分。

**Comment by jjdddn1** [comment]
好的~

**Comment by GreatYYX** [comment]
有点动摇合并接口的问题了，因为多了一个不合并chat接口的理由。拿微信来举例子：当私聊的两人中（A、B）有一个人拉入一个新人后（C），相当于重新开辟了一个聊天室（含有A、B、C），但是私聊关系依然存在（A、B）。但如果在这个行聊天室中加入D（A、B、C、D），并没有再开辟新聊天室。也就是说，私聊关系是固定的。从后端角度说，私/群聊数据库就会分开做，这样可以针对性优化；但是对于接口，虽然可以统一一部分（诸如未读消息的接口相对难做整合），但是现在对于群聊由于前端还没有做也没有push老板，因此可能还有很多特性到时候会被深挖或者废除，因此目前还是保留两套接口更为合理。 @mingjiej @maplestory06

**Comment by GreatYYX** [comment]
@mingjiej 勿忘传达一下服务器不保存聊天记录只做转发的想法。
