### ISSUE TITLE
last_login_at: 关于这个接口的逻辑疑问

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#57]
根据协议里写的，
GET /users/account 需要auth，
然而，获取auth的条件是需要login以后的那个auth字段，
因此，我可不可以认为last_login_at这个存在于GET /users/account里的返回字段永远不会为null。
既然永远不会为null，那么前端就无从判断是否是第一次登录

**Comment by GreatYYX** [comment]
thanks, it will be added to get profile soon

**Comment by joshuayueshen** [comment]
此外，如果加在GET profile里，那么逻辑还是有点问题，以上的情况可能还是会发生。
可否这样，每当用户更新自身坐标的时候（POST /map/user），就更新last_login_at，可以吗？
