### ISSUE TITLE
commentController里边getFromUser

### ISSUE THREAD

**Issue by kaiqianz** [letsfae/Fae-Backend#60]
这个方法里边
            $user_pin_operations = PinOperationController::getOperations('comment', $comment->id, $this->request->self_user_id);
这个$this->request->self_user_id应该为参数中的$user_id.和getone方法一致
![screen shot 2017-02-17 at 2 04 21 pm](https://cloud.githubusercontent.com/assets/16984097/23085002/03a3468e-f51a-11e6-9187-ba5a4e0f51b0.png)

@MrBlueberry

**Comment by kaiqianz** [comment]
user_id为那个comment对应的user_id

**Comment by MrBlueberry** [comment]
。。。。。。。。。这是用户本身对该comment的操作···你先去弄清楚这个参数id以及pin operation是干啥的
