### ISSUE TITLE
[获取saved Places] 需要一个GET Saved Places的API。获取用户储存的所有Places的信息，传入参数是user Id, 当前经纬度。返回值包括place的所有信息和与当前位置的距离。

### ISSUE THREAD

**Issue by weishiqi** [letsfae/Fae-Backend#69]

**Comment by GreatYYX** [comment]
如果不需要与当前位置的距离 可以直接使用get map接口，把is_saved设置为true就行

**Comment by GreatYYX** [comment]
还有我不是很清楚place和location的区别？后端能返回位置的只有media pin, comment pin, chat_room pin和user pin，所以这儿place是指所有pin?那location是什么。。。

**Comment by weishiqi** [comment]
place是地图上yelp那些餐厅啊之类的地点，location这个我也要再确认一下到底是哪些数据。

**Comment by GreatYYX** [comment]
...这东西叫place啊 我直接叫它business pin了……目前UI上是叫place吗？

**Comment by weishiqi** [comment]
对的 但我不确定这个是叫place还是叫location。pin 是只有 media， chat，and comment。
