### ISSUE TITLE
需要有让用户保存location和yelp api返回的店家

### ISSUE THREAD

**Issue by mingjiej** [letsfae/Fae-Backend#71]
location至少要有经纬度和一张缩略图，图可以压缩字符串的形式从前端提供，如果可以需要添加地址第一行，第二行，第三行，比如“123 main street”,"Los Angeles, California 90007", "United State"
Yelp api就是api提供的信息

**Comment by GreatYYX** [comment]
爬虫 @SonnyYang 已经在弄了 你们对于店家这类的pin的接口有没有什么要求

**Comment by mingjiej** [comment]
参照https://www.yelp.com/developers/documentation/v3/business_search
给出的response范例
businesses 中返回：

"categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "name": "Four Barrel Coffee",
      "url": "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      "coordinates": {
        "latitude": 37.7670169511878,
        "longitude": -122.42184275
      },
      "image_url":
"http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      "location": {
        "city": "San Francisco",
        "country": "US",
        "address2": "",
        "address3": "",
        "state": "CA",
        "address1": "375 Valencia St",
        "zip_code": "94103"
      },


这些


2017-02-28 20:54 GMT-08:00 GreatYYX <notifications@github.com>:

**Comment by GreatYYX** [comment]
yelp的那种点我们已经命名成place了 关于location 相当于就是自定义的mark对吧

**Comment by mingjiej** [comment]
可以

Thank you

Mingjie Jin
