### ISSUE TITLE
pinoperationCOntroller里边，UpdateResourceFailedException这个不存在，应该换成StoreResourceFailedException

### ISSUE THREAD

**Issue by kaiqianz** [letsfae/Fae-Backend#74]
如果最新的错误返回已经更改，直接关闭即可。
![screen shot 2017-03-06 at 5 04 10 pm](https://cloud.githubusercontent.com/assets/16984097/23637194/27a5de20-028f-11e7-970b-7d48be79a640.png)
@MrBlueberry

**Comment by MrBlueberry** [comment]
所有的错误返回由我定义。没有错误之说。所有这类问题不是错误。
