### ISSUE TITLE
[需求 - Pin Detail] 用户对Pin的心情，一共11种

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#75]
![image](https://cloud.githubusercontent.com/assets/18542103/23814945/7e38e6ca-059a-11e7-916b-f82fd6344c1f.png)
如图下方显示，后端是否可以在对pin的操作里增加这种心情，只需要使用Int类型作为其value即可。

**Comment by GreatYYX** [comment]
这是出现在哪儿的，是在pin的comment里面？

**Comment by joshuayueshen** [comment]
不属于pin的comment，算是对pin的心情的表态。目前已有的例子就是Facebook按赞的时候有不同的赞的方法，有大笑、伤心、怒气以及普通的赞

**Comment by GreatYYX** [comment]
这个feeling，对于每个pin可以有几个

**Comment by joshuayueshen** [comment]
@GreatYYX 每个用户对一个pin只能有一个feeling，但是feeling和like是可以同时出现，like功能已经实现
在获取user对于pin的action的时候，需要获取哪些user like这个pin以及那些人对这个pin有feeling

**Comment by GreatYYX** [comment]
好 可是为何你给我的图 最下面感觉有3个feeling

**Comment by joshuayueshen** [comment]
![image](https://cloud.githubusercontent.com/assets/18542103/24127820/d9a85eb2-0d94-11e7-8223-2b5643b994e1.png)
你是说这里吗？
这个是这个pin已有的feeling的一个briefly show

**Comment by GreatYYX** [comment]
好 那到时候这个brief show你怎么统计呢。。。

**Comment by joshuayueshen** [comment]
get pin的时候返回每个feeling的count数量。
这个有点细节，为了优化前端后端的数据发送和处理，周三是否有空见个面？

**Comment by GreatYYX** [comment]
我只能周末 平时可以电话 这周末如果要见面可以在周六下午（2点后，中午和周日之后晓睿有事）
