### ISSUE TITLE
[需求 - namecard] 将user_name字段加入用户namecard的json返回值里

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#76]
如题
@GreatYYX

**Comment by GreatYYX** [comment]
这个确定吗？因为我记得namecard是在地图上点user pin之后显示的，不能直接关联到用户，所以我连user id都没提供，老板当时和我说只需要显示nick name一种name啊。

**Comment by joshuayueshen** [comment]
是的，你说的没错。
问题是，现在在pin detail里有个页面叫做people，这个页面中不仅要显示nickname还要显示username
如果我用namecard仅仅获得了nickname，还得再用相同的user id获取username，非常繁琐

**Comment by GreatYYX** [comment]
@maplestory06 要不再和老板核对一下 namecard这地方要统一 既然不能获取用户真实信息那就都不能获取 否则我直接给你user_id 但这样的话相当于这个namecard就不再保护隐私了

**Comment by joshuayueshen** [comment]
@GreatYYX 我和你微信语音说
