### ISSUE TITLE
[获取my pins的count] 另外需要一个API 获取mypins里pins的总数量。只返回一个count的字段就好

### ISSUE THREAD

**Issue by weishiqi** [letsfae/Fae-Backend#77]

**Comment by GreatYYX** [comment]
是不是获取数量的时候也是要获取pin本身的 如果是我直接就把count整合到获取mypin的接口里

**Comment by weishiqi** [comment]
只要获取一个count,不需要获取pin本身。

**Comment by GreatYYX** [comment]
我想知道一下应用场景 比如如果是只要显示数量 用不到获取mypin的情况 那有单独提供接口的必要 
否则则没有必要比如你的界面是选项卡 用户只要点开就要显示 那不妨我给你在原接口中添加count字段 你一次抓取能获得count以及几条数据 等选项卡切换的时候直接把这些数据显示出来就行 如果要更多的数据则再请求 相当于第一次直接给你一部分冗余数据 这也是大多app用于初始化UI的方法 相当于每次给你一部分冗余数据 如果用户有请求倾向则再获取 这样request次数可以显著减少 而对于数据的冗余开销也比较小

**Comment by weishiqi** [comment]
是在要显示mypins的选项button上要显示总的item个数，然后点这个button之后才去获取显示具体的内容，再在新的view上显示。所以需要一个接口来单独获取count。

**Comment by weishiqi** [comment]
可以设计成第一次直接给一部分冗余数据。然后用户点进去的时候我再显示具体的内容。
