### ISSUE TITLE
[获取saved places的count] 另外需要一个API 获取savedplaces里places的总数量。只返回一个count的字段就好

### ISSUE THREAD

**Issue by weishiqi** [letsfae/Fae-Backend#79]

**Comment by GreatYYX** [comment]
places不属于pin? 为何saved places count和saved pin count是分开的

**Comment by GreatYYX** [comment]
对了还包括location, 难倒现在是pin, location, places这样？对后端来说都是pin呀。要不我给你一个总的统计接口，这样我把每个条目分别返回，你就可以用了。（另，下次相同类别的发一个issue就好啦）

**Comment by weishiqi** [comment]
![image](https://cloud.githubusercontent.com/assets/14206632/24685840/e2adff22-1964-11e7-9fda-0ffbace81db8.png)
是分开的，这个是前段这块的一个board图。

**Comment by weishiqi** [comment]
就目前老板给的设计图来看 pin place location 是分开存的 而且place跟location的表里面还应该有一个字段是memo。因为用户可以对place跟location加memo。

**Comment by GreatYYX** [comment]
OK 我会给你们加上memo字段 这个就可以用统一的接口获取呀。。。不是说后端一个接口就要对应前端一个界面的 有时候一个接口可以对应好几个 比如我给你一个总的count 甚至是不同count的具体数据给你5条 这样你一次获取就可以完成这个统计界面及每个子界面的初始化

**Comment by GreatYYX** [comment]
所以就是说 获取mypin那个接口 要排除location?

**Comment by weishiqi** [comment]
mypins 其实是界面里的created pins. location 跟 place是另外存的。location我还没确定定义，但是这俩肯定都不是在mypins里。
