### ISSUE TITLE
name card 图片接口

### ISSUE THREAD

**Issue by blesssecret** [letsfae/Fae-Backend#8]
老姚，namecard 有一个 change cover photo 接口，这个和头像是一样的，我在查文档的时候没有找到，能提供一个么？

**Comment by GreatYYX** [comment]
https://github.com/letsfae/Fae-Backend/blob/master/docs_zh_cn/protocol_files.md#设置namecard背景图片-white_check_mark
https://github.com/letsfae/Fae-Backend/blob/master/docs_zh_cn/protocol_files.md#获取namecard背景图片-white_check_mark
https://github.com/letsfae/Fae-Backend/blob/master/docs_zh_cn/protocol_files.md#获取其他用户namecard背景图片-white_check_mark
