### ISSUE TITLE
[用户认证类 - existence of username] aAa应该与AAA为相同的username

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#83]
检查用户名是否存在的时候，aAa和AAA应该是相同的username，但是在检查existence的时候后端返回existence = false

麻烦修正一下，辛苦后端了

**Comment by GreatYYX** [comment]
OK 用户名本身有大小写 但是用户名判重时候对大小写不敏感 @MrBlueberry 修正一下ExistenceController的判断
