### ISSUE TITLE
[Pin-Action Feeling] 每个user一个pin只能有一种feeling，目前是多种，可更改feeling

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#85]
如题

谢谢后端，辛苦你们了

**Comment by MrBlueberry** [comment]
目前不是多种，一个USER对一个PIN只有一种feeling，而且可以更改，update和create是同一个接口，delete是另一个接口。

**Comment by joshuayueshen** [comment]
麻烦再多检查一下？
![image](https://cloud.githubusercontent.com/assets/18542103/24490665/70dd66ca-14d8-11e7-8c18-d6c549b61e6a.png)

**Comment by joshuayueshen** [comment]
以上是我对一个pin的单个用户操作

**Comment by GreatYYX** [comment]
feeling count 返回为何不是number...

**Comment by joshuayueshen** [comment]
这个无所谓了，我前端会处理。

**Comment by GreatYYX** [comment]
@MrBlueberry 可是协议上是int，而且别的count都是number，这儿是str…… 
```
"feelings_count": [
	@number,
	...
],
```
