### ISSUE TITLE
[Pin-Action] 需求：哪些用户对pin有action

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#86]
根据老板的需求，
在pin里需要显示哪些用户对该pin进行了操作
只需要如下几个：
1. like （暂无，仅有count）
2. comment （已有，both count and list）
3. feeling （暂无，仅有count）

辛苦后端了，这块做完，pin detail大体上告一段落

**Comment by GreatYYX** [comment]
一定要有吗。。。或者能不能固定一个数量，因为这类反查的统计信息如果动态查询非常浪费查询时间 而且这个数据量可能是巨大的
或者替代方案是只显示count，当用户访问到相关界面的时候再次请求相关接口去获取，因为这些如果真的完全整合到一个接口，相当于前端一次查询，数据库实际上发起好几次查询（join），而且当数据量很大时候，还涉及到嵌套分页的问题，这个会很蛋疼（固定显示数量可以解决嵌套分页）

**Comment by joshuayueshen** [comment]
嗯，我和老板商量一下，这是他的图里给的信息。
