### ISSUE TITLE
[chat_room] 需求更新：需要一张chat_room的图片，已加入chat_room的用户id

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#88]
创建chat_room，目前有capacity，但是没有具体哪些用户加入的信息，有点不合理。

并且在地图上，用户打开这个chat_room pin的时候需要看到这个chat_room有哪些人，还剩下多少的名额。

老板的图如下：
![image](https://cloud.githubusercontent.com/assets/18542103/24841772/9117e95e-1d40-11e7-8672-c8274a29c666.png)

**Comment by GreatYYX** [comment]
OK 看来前端开始实现群聊接口了 我会给你们提供image接口 也会给你在get的时候加入群的用户信息

**Comment by GreatYYX** [comment]
另外，获取某个chatroom的用户可以通过这个接口https://github.com/letsfae/FaeMap-Backend/blob/master/docs_zh_cn/protocol_chats.md#获取chatroom中所有用户-white_check_mark。 

用户信息我会添加到pin级别的接口中用于你上图的显示（chatroom有pin级别接口和chat级别的接口），但对于chat级别接口，我不建议在获取聊天列表的时候同时给你chatroom的用户，你可以在用到的时候调用获取用户的接口（参考微信群聊中点用户列表后才加载列表），因为很多时候，有些群聊并不会点进去，即使进去了不一定会去看用户列表。

**Comment by joshuayueshen** [comment]
谢谢，这很合理
