### ISSUE TITLE
[pin_action - feeling] 用户需要知道ta给pin留下了哪个feeling

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#89]
@GreatYYX 老姚，看来这个是必须做了，之前的逻辑我现在回想起来发觉有问题。
如下图：
![image](https://cloud.githubusercontent.com/assets/18542103/24948609/af2f4604-1f1f-11e7-9115-533465efc019.png)
当用户点开一个pin，如果用户留下了feeling，那么相应的feeling的button的size会被放大，否则是small size。

以上的需求的另外两个必要性是：
1. 用户在点击已经posted的feeling的button的时候，相当于一次delete操作，所以系统需要判断该feeling是否被用户posted，如果是，则执行delete，否则update feeling to another feeling
2. 在people这个table里显示用户对改pin进行了何种操作

还请老姚斟酌一下，谢啦。辛苦你们了。

**Comment by joshuayueshen** [comment]
btw，以上这幅图是用户未展开pin的时候选择feeling的方式，
上次那幅图是用户展开pin后选择feeling的方式。

**Comment by GreatYYX** [comment]
[feeling的加入和删除](https://github.com/letsfae/FaeMap-Backend/blob/master/docs_zh_cn/protocol_pins.md)接口已经有了（抱歉我忘了标记打钩了）。在对应的pin中，也有两个字段（可参考[“获取comment”中的字段](https://github.com/letsfae/FaeMap-Backend/blob/master/docs_zh_cn/protocol_maps.md#获取comment-white_check_mark)）用于获取用户对于该pin的feelings操作。
