### ISSUE TITLE
BlockController里边Add方法是不是要判断self_user_id和requested_user_id是同一个的情况

### ISSUE THREAD

**Issue by kaiqianz** [letsfae/Fae-Backend#90]
<img width="729" alt="screen shot 2017-04-12 at 3 30 41 pm" src="https://cloud.githubusercontent.com/assets/16984097/24982190/0482098c-1f95-11e7-8daf-ac3f7608822f.png">
@MrBlueberry

**Comment by GreatYYX** [comment]
block这块我记得是 @SonnyYang 的代码好像
