### ISSUE TITLE
用户可以删除自己my pins里的pin。

### ISSUE THREAD

**Issue by weishiqi** [letsfae/Fae-Backend#94]
用户可以对自己创建的pin有删除操作，我在api里没有找到这条。如果没有这个api请加上，有的话请跟我说一声。谢谢后段。

**Comment by weishiqi** [comment]
我找到了api方法，但是api文档里没有写。

**Comment by GreatYYX** [comment]
所有的pin（不包括chatroom pin）都有5大接口 create update getOneById getAllByUserId delete
具体参考这儿 https://github.com/letsfae/FaeMap-Backend/blob/master/docs_zh_cn/protocol_maps.md
