### ISSUE TITLE
[需求] Allow user to Report, Feedback.

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-Backend#97]
Report需要的字段：
1. report的种类（在前端有不同种的report，是否可以由前端来决定？），这个字段不经由用户填写，由前端填写。（ex. 举报用户，举报带有不良信息的place，带有不良信息的pin等等）
2. feedback，前端有专门一个页面给用户填写用户调研的

还请和我沟通具体细节

**Comment by GreatYYX** [comment]
1.我建议由后端来做 而且不同type我记得要对应不同的邮箱 当然我们也可以把email和type的权限都开放给你们
2.feedback这个难道不是report？

**Comment by joshuayueshen** [comment]
嗯，就照着你们方便的来。feedback也可以是report，也放在category就行，这样确实方便点

**Comment by GreatYYX** [comment]
所以前端需要扩展哪些type，这些type需要有怎么样的行为，需要发送到哪个邮箱请都反馈给我。目前的feedback接口在这儿https://github.com/letsfae/FaeMap-Backend/blob/master/docs_zh_cn/protocol_others.md#反馈接口-white_check_mark

**Comment by joshuayueshen** [comment]
谢谢~
